# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: app-service
  type: ClusterIP
  ports:
  - name: app-service
    protocol: TCP
    port: 80
    targetPort: 8080
