apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis
  namespace: default
  labels:
    app:  redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
    spec:
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
      - name:  redis
        image:  redis:7.2.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
        args: ["--requirepass", "somepassword", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
      restartPolicy: Always


