services:
  redis: 
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass somepassword 
    volumes:
      - cache:/data

  api:
    depends_on: [redis]
    build: . 
    ports:
      - "8080:8080"
    volumes:
      - ./configs/:/app/configs

volumes:
  cache:
    driver: local
