app:
  env: "dev"

httpServer:
  host: "0.0.0.0"
  port: 8080

logging:
  stdout: true
  level: "debug"

redis:
  address: "redis:6379"
  password: ""
  DB:  0
  dialTimeout: "5s"
  readTimeout: "3s"
  writeTimeout: "3s"
